sonar.organization=pierfreeman
sonar.projectKey=pierfreeman_saas-frontend-blueprint

sonar.sources=apps,libs
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,coverage/**,tmp/**
sonar.coverage.exclusions=**/vitest.config.ts,**/vitest.workspace.ts

sonar.tests=apps,libs
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/**/lcov.info
sonar.typescript.tsconfigPath=tsconfig.base.json
