#!/usr/bin/env bash
# scripts/generate-env.sh
#
# Writes environment.prod.ts (and remotes.json for shell) from Vercel env vars.
# Run this BEFORE `nx build` so the compiler picks up the generated files.
#
# Usage: bash scripts/generate-env.sh <app>
#   where <app> is one of: shell | auth | platform | admin
#
# Required environment variables per app:
#   ALL:      API_BASE_URL
#   shell:    AUTH0_DOMAIN, AUTH0_CLIENT_ID, AUTH0_AUDIENCE, AUTH0_REDIRECT_URI,
#             REMOTE_AUTH_URL, REMOTE_PLATFORM_URL, ADMIN_API_URL, ADMIN_APP_URL
#   platform: STRIPE_PRICE_ID
#   admin:    ADMIN_API_URL, ADMIN_AUTH0_DOMAIN, ADMIN_AUTH0_CLIENT_ID,
#             ADMIN_AUTH0_AUDIENCE, ADMIN_AUTH0_REDIRECT_URI

set -euo pipefail

APP="${1:?First argument must be the app name (shell | auth | platform | admin)}"

require_var() {
  local var="$1"
  if [[ -z "${!var:-}" ]]; then
    echo "ERROR: Required environment variable '$var' is not set." >&2
    exit 1
  fi
}

case "$APP" in
  shell)
    require_var API_BASE_URL
    require_var ADMIN_API_URL
    require_var ADMIN_APP_URL
    require_var AUTH0_DOMAIN
    require_var AUTH0_CLIENT_ID
    require_var AUTH0_AUDIENCE
    require_var AUTH0_REDIRECT_URI
    require_var REMOTE_AUTH_URL
    require_var REMOTE_PLATFORM_URL

    # Generate environment.prod.ts — overrides the placeholder file in git
    cat > apps/shell/src/environments/environment.prod.ts << EOF
// Generated by scripts/generate-env.sh — do not edit manually.
export const environment = {
  production: true,
  apiUrl: '${API_BASE_URL}',
  adminApiUrl: '${ADMIN_API_URL}',
  adminAppUrl: '${ADMIN_APP_URL}',
  auth0Domain: '${AUTH0_DOMAIN}',
  auth0ClientId: '${AUTH0_CLIENT_ID}',
  auth0Audience: '${AUTH0_AUDIENCE}',
  auth0RedirectUri: '${AUTH0_REDIRECT_URI}',
};
EOF

    # Generate remotes.json into public/ so Angular CLI copies it to the dist root.
    # Admin is now a standalone app and is NOT a federated remote.
    cat > apps/shell/public/remotes.json << EOF
{
  "auth": "${REMOTE_AUTH_URL}/remoteEntry.js",
  "platform": "${REMOTE_PLATFORM_URL}/remoteEntry.js"
}
EOF

    echo "[generate-env] shell: environment.prod.ts and remotes.json written."
    ;;

  auth)
    require_var API_BASE_URL

    cat > apps/auth/src/environments/environment.prod.ts << EOF
// Generated by scripts/generate-env.sh — do not edit manually.
export const environment = {
  production: true,
  apiUrl: '${API_BASE_URL}',
};
EOF
    echo "[generate-env] auth: environment.prod.ts written."
    ;;

  platform)
    require_var API_BASE_URL
    # STRIPE_PRICE_ID is optional (falls back to empty string)
    STRIPE_PRICE_ID="${STRIPE_PRICE_ID:-}"

    cat > apps/platform/src/environments/environment.prod.ts << EOF
// Generated by scripts/generate-env.sh — do not edit manually.
export const environment = {
  production: true,
  apiUrl: '${API_BASE_URL}',
  stripePriceId: '${STRIPE_PRICE_ID}',
};
EOF
    echo "[generate-env] platform: environment.prod.ts written."
    ;;

  admin)
    require_var ADMIN_API_URL
    require_var ADMIN_AUTH0_DOMAIN
    require_var ADMIN_AUTH0_CLIENT_ID
    require_var ADMIN_AUTH0_AUDIENCE
    require_var ADMIN_AUTH0_REDIRECT_URI

    cat > apps/admin/src/environments/environment.prod.ts << EOF
// Generated by scripts/generate-env.sh — do not edit manually.
export const environment = {
  production: true,
  adminApiUrl: '${ADMIN_API_URL}',
  auth0Domain: '${ADMIN_AUTH0_DOMAIN}',
  auth0ClientId: '${ADMIN_AUTH0_CLIENT_ID}',
  auth0Audience: '${ADMIN_AUTH0_AUDIENCE}',
  auth0RedirectUri: '${ADMIN_AUTH0_REDIRECT_URI}',
};
EOF
    echo "[generate-env] admin: environment.prod.ts written."
    ;;

  *)
    echo "ERROR: Unknown app '$APP'. Must be one of: shell | auth | platform | admin" >&2
    exit 1
    ;;
esac
